### ISSUE TITLE
Cache Exception before Http404

### ISSUE THREAD

**Issue by backendrulz** [LeaguePHP/LeagueWrap#7]
![seleccion_046](https://cloud.githubusercontent.com/assets/817816/20538428/f5f31da4-b0cf-11e6-8984-10f9b025cedd.png)

This exception (cache) is before "LeagueWrap\Response\Http404"

"Dayz6546465" Is a non-existent summoner name

Exception in Cache.php line 31:
`return $this->memcached->set($key, $response, $seconds);`

Is trying to save $reponse as Http404 exception.

**Comment by m1so** [comment]
The issues should be [fixed](https://github.com/LeaguePHP/LeagueWrap/commit/628d2132bdae564de4d1699795c323aa18bbf323) now. There was a problem with serializing exception's stack trace, which has been resolved with help of [Fabien Potencier's article](http://fabien.potencier.org/php-serialization-stack-traces-and-exceptions.html).

Caching error responses (4xx or 5xx) might not be the best idea due to issues on Riot's side (see https://github.com/paquettg/leaguewrap/issues/119). Consider using `setClientErrorCaching` or `setServerErrorCaching` methods on the `Api` class to set the caching preferences.
